# Generated by Django 2.1.2 on 2018-10-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientininventory',
            old_name='ingredientID',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='ingredientID',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='recipeID',
            new_name='recipe',
        ),
    ]
