# Generated by Django 2.1.2 on 2018-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientininventory_ndbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientininventory',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
    ]
