# Generated by Django 2.1.2 on 2018-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20181103_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='measurement',
            field=models.CharField(choices=[('lbs', 'pounds'), ('oz', 'ounces'), ('floz', 'fluid ounces'), ('g', 'grams')], max_length=4),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(choices=[('lbs', 'pounds'), ('oz', 'ounces'), ('floz', 'fluid ounces'), ('g', 'grams')], max_length=4),
        ),
    ]
