# Generated by Django 2.1.2 on 2018-10-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20181024_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientInInventory',
            new_name='Inventory',
        ),
    ]
