# Generated by Django 2.1.2 on 2018-10-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20181024_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplied_from',
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Supplier'),
            preserve_default=False,
        ),
    ]
