# Generated by Django 2.1.2 on 2018-10-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20181024_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='supplier',
            new_name='supplied_by',
        ),
    ]
